/**
 * Native presentation tokens aligned with the light Web client. Keeping the
 * tokens in one object prevents screen-specific copies of the sidebar, text,
 * and composer colours.
 */
export const mobileTheme = {
  colors: {
    background: '#ffffff',
    canvas: '#ffffff',
    drawerBackground: '#f9fafb',
    surface: '#ffffff',
    surfaceRaised: '#ffffff',
    surfaceMuted: '#f5f6f7',
    surfaceActive: '#ebeef2',
    ink: '#0f1115',
    inkMuted: '#61666b',
    inkFaint: '#adb2b8',
    border: '#e1e5ee',
    borderStrong: '#d1d5db',
    accent: '#4176e6',
    textOnAccent: '#ffffff',
    accentText: '#1d4ed8',
    accentSoft: '#e4edfd',
    success: '#22c55e',
    successText: '#15803d',
    successSoft: '#e6faed',
    warning: '#dd8629',
    warningText: '#9a5a00',
    warningSoft: '#fef5e7',
    danger: '#ec1313',
    dangerSoft: '#fef2f2',
    userBubble: '#edf3fe',
    assistantBubble: '#ffffff',
    agentBubble: '#f7f6f2',
    overlay: 'rgba(15, 17, 21, 0.38)',
    codeBackground: '#1b1b1c',
    codeForeground: '#e4eaf3',
  },
  radius: { xs: 4, card: 10, control: 8, bubble: 12, composer: 22, sheet: 20, pill: 999 },
  spacing: { xxs: 2, xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 },
  typography: { eyebrow: 11, caption: 12, body: 14, bodyLarge: 15, title: 22, lineBody: 21 },
  rail: { width: 56, button: 36, gap: 12 },
  chrome: {
    headerHeight: 48,
    headerMetaHeight: 35,
    headerWithMetaHeight: 83,
    tabHeight: 35,
    composerRadius: 22,
    controlHeight: 36,
  },
  touch: { iconButton: 44, compactIconButton: 36, controlHeight: 40, minTarget: 44 },
  elevation: {
    card: {
      shadowColor: '#172033',
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    sheet: {
      shadowColor: '#172033',
      shadowOpacity: 0.12,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: -6 },
      elevation: 8,
    },
  },
} as const
